version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      -8585:80
    environment: #same as -e in docker run command
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./wordpress-data:/var/www/html
  
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql-data:/var/lib/mysql