# Drupal with PostgreSQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: example
# ADVANCED OPTIONS; Database host: postgres

version: '3.1'

services:

  drupal:
    image: custom-drupal:latest
    ports:
      - 8080:80
    volumes:
#      - /var/www/html/modules
      - drupal-modules:/var/www/html/modules
#      - /var/www/html/profiles
      - drupal-profiles:/var/www/html/profiles
#      - /var/www/html/themes
      - drupal-sites:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
#      - /var/www/html/sites
      - drupal-themes:/var/www/html/sites
    restart: always

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      #for database to persist across compose restarts
      - drupal-data:/var/lib/postgresql/data
    restart: always
  
volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    drupal-data: