# Use an official Python runtime as a parent image ​

FROM python:3

# Set the working directory to /app ​

WORKDIR /app ​

# Copy the current directory contents into the container at /app ​

COPY app.py /app

# Add the archive packages specified in require.txt ​

ADD requires.txt requires.txt

# Install any needed packages specified in require.txt ​

RUN pip install --trusted-host pypi.python.org -r requires.txt

# Make port 80 available to the world outside this container ​

EXPOSE 80​

# Define environment variable ​

ENV NAME World ​

# Run app.py when the container launches ​

CMD ["python", "app.py"]